name: godocs.yml
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

env:
  GO_VERSION: '1.24'

jobs:
  update-go-docs:
    name: Update Go Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main and all tags
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Verify tag is on main branch
        run: |
          if git branch -r --contains ${{ github.ref_name }} | grep -qw "origin/main"; then
            echo "✅ Tag ${{ github.ref_name }} found on main branch."
          else
            echo "❌ Tag ${{ github.ref_name }} is not on main branch. Aborting."
            exit 1
          fi

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Ping Go Proxy
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/${{ github.repository }}@${{ github.ref_name }}